' Welcome to vizard.io
' This diagram will be auto-saved in your browser
'
' For syntax see PlantUML Language Reference Guide:
' http://plantuml.sourceforge.net/PlantUML_Language_Reference_Guide.pdf


class User{
  Integer id
  String reference
  String name

  Integer score()
}

class Device{
  Integer id
  String reference
  String name
  Enum strategy <countdown/duration/onetime>

  'void methods()
}

class Task{
  Integer id
  Integer user_id
  Integer device_id
  Integer points
  String state <running/finished>

  'void methods()
}

class Event{
  Integer id
  String device_reference
  String user_reference
  Datetime timestamp
  Enum type <start/end>

  'void methods()
}

/'
class StatusEvent{
  Integer id
  String device_reference
  Datetime timestamp

  'void methods()
}
'/


User  --> "*" Task
Device --> "*" Task
Task --> "2" Event

'Device --> "*" StatusEvent
